=== cosmos/wallet-registry/wallet.schema.json
{
  "$schema": "https://json-schema.org/draft-07/schema",
  "title": "Cosmos Wallet",
  "description": "Cosmos Wallet.json is a metadata file that contains information about a wallet of a specific platform and which chains it supports, either natively or via custom client-side addition.",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "wallet_name": {
      "type": "string",
      "pattern": "[a-z]+"
    },
    "pretty_name": {
      "type": "string"
    },
    "website": {
      "type": "string",
      "format": "url"
    },
    "git_repo": {
      "type": "string",
      "format": "url"
    },
    "supported_chains": {
      "type": "array",
      "items": {
        "type": "string",
        "pattern": "[a-z0-9]+"
      },
      "minContains": 1
    },
    "features": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "suggest_chain",
          "get_supported_chains",
          "icns"
        ]
      }
    },
    "platforms": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "device": {
            "type": "string",
            "enum": [
              "mobile",
              "tablet",
              "desktop",
              "other"
            ]
          },
          "type": {
            "type": "string",
            "enum": [
              "application",
              "extension"
            ]
          },
          "platform": {
            "type": "string",
            "enum": [
              "chrome",
              "firefox",
              "ios",
              "android",
              "otherOS",
              "otherBrowser"
            ]
          },
          "install_link": {
            "type": "string",
            "format": "uri"
          }
        },
        "additionalProperties": false,
        "required": [
          "device",
          "type",
          "platform"
        ]
      },
      "minContains": 1
    }
  },
  "additionalProperties": false,
  "required": [
    "$schema",
    "wallet_name",
    "pretty_name",
    "platforms",
    "supported_chains"
  ]
}

=== cosmos/wallet-registry/wallets/leapmobile.json
{
  "$schema": "../wallet.schema.json",
  "wallet_name": "leapmobile",
  "pretty_name": "Leap cosmos",
  "website": "https://leapwallet.io",
  "git_repo": "",
  "supported_chains": [
    "cosmoshub",
    "juno",
    "osmosis",
    "akash",
    "assetmantle",
    "axelar",
    "cheqd",
    "chihuahua",
    "desmos",
    "emoney",
    "fetchhub",
    "gravitybridge",
    "injective",
    "irisnet",
    "jackal",
    "kujira",
    "likecoin",
    "persistence",
    "atlantic",
    "sifchain",
    "sommelier",
    "stargaze",
    "starname",
    "stride",
    "teritori",
    "umee"
  ],
  "platforms": [
    {
      "device": "mobile",
      "type": "application",
      "platform": "ios",
      "install_link": "https://apps.apple.com/in/app/leap-cosmos/id1642465549"
    },
    {
      "device": "mobile",
      "type": "application",
      "platform": "android",
      "install_link": "https://play.google.com/store/apps/details?id=io.leapwallet.cosmos"
    }
  ]
}

=== cosmos/wallet-registry/wallets/leapextension.json
{
  "$schema": "../wallet.schema.json",
  "wallet_name": "leapextension",
  "pretty_name": "Leap Cosmos Wallet",
  "website": "https://www.leapwallet.io/",
  "git_repo": "",
  "supported_chains": [
    "cosmoshub",
    "juno",
    "osmosis",
    "secretnetwork",
    "agoric",
    "akash",
    "assetmantle",
    "axelar",
    "bitsong",
    "cheqd",
    "chihuahua",
    "comdex",
    "desmos",
    "emoney",
    "evmos",
    "fetchhub",
    "gravitybridge",
    "injective",
    "irisnet",
    "jackal",
    "kujira",
    "likecoin",
    "persistence",
    "atlantic",
    "sifchain",
    "sommelier",
    "stargaze",
    "starname",
    "stride",
    "teritori",
    "umee"
  ],
  "features": ["suggest_chain"],
  "platforms": [
    {
      "device": "desktop",
      "type": "extension",
      "platform": "chrome",
      "install_link": "https://chrome.google.com/webstore/detail/leap-cosmos-wallet/fcfcfllfndlomdhbehjjcoimbgofdncg"
    }
  ]
}

=== cosmos/wallet-registry/wallets/cosmostationextension.json
{
  "$schema": "../wallet.schema.json",
  "wallet_name": "cosmostationextention",
  "pretty_name": "Cosmostation",
  "website": "https://www.cosmostation.io/",
  "git_repo": "https://github.com/cosmostation/cosmostation-chrome-extension",
  "supported_chains": [
      "cosmoshub",
      "akash",
      "assetmantle",
      "axelar",
      "bandchain",
      "bitcanna",
      "bitsong",
      "canto",
      "cerberus",
      "chihuahua",
      "comdex",
      "coreum",
      "crescent",
      "cryptoorgchain",
      "cudos",
      "desmos",
      "emoney",
      "evmos",
      "fetchhub",
      "gravitybridge",
      "injective",
      "irisnet",
      "impacthub",
      "juno",
      "kava",
      "kichain",
      "konstellation",
      "kujira",
      "kyve",
      "likecoin",
      "lumnetwork",
      "neutron",
      "noble",
      "nyx",
      "omniflixhub",
      "onomy",
      "osmosis",
      "panacea",
      "passage",
      "persistence",
      "provenance",
      "quasar",
      "regen",
      "rizon",
      "secretnetwork",
      "sentinel",
      "shentu",
      "sifchain",
      "sommelier",
      "stafihub",
      "stargaze",
      "starname",
      "stride",
      "teritori",
      "tgrade",
      "umee"
  ],
  "features": [
    "suggest_chain",
    "icns"
  ],
  "platforms": [
    {
      "device": "desktop",
      "type": "extension",
      "platform": "chrome",
      "install_link": "https://chrome.google.com/webstore/detail/cosmostation/fpkhgmpbidmiogeglndfbkegfdlnajnf?utm_source=chrome-ntp-icon"
    }
  ]
}

=== cosmos/wallet-registry/wallets/trustwalletmobile/wallet.json
{
  "$schema": "../../wallet.schema.json",
  "wallet_name": "trustwalletmobile",
  "pretty_name": "Trust Wallet",
  "website": "https://www.trustwallet.com",
  "git_repo": "https://github.com/trustwallet",
  "supported_chains": [
    "cosmoshub",
    "osmosis",
    "cryptoorgchain",
    "terra",
    "evmos",
    "kava",
    "thorchain"
  ],
  "platforms": [
    {
      "device": "mobile",
      "type": "application",
      "platform": "ios",
      "install_link": "https://apps.apple.com/app/apple-store/id1288339409"
    },
    {
      "device": "mobile",
      "type": "application",
      "platform": "android",
      "install_link": "https://play.google.com/store/apps/details?id=com.wallet.crypto.trustapp"
    }
  ]
}
